version: '3.3'
services:
  redis:
    image: "redis"
    # ports:
    #   -"6379:6379"
    expose:
      - 6379
    volumes:
      - db_data:/data
  web:
    depends_on:
      - redis
    links:
      - redis
    environment:
      host: redis
    # build: .
    image: "laure15a/devops_project"
    ports:
      - "3000:3000"
volumes:
  db_data: {}
