---

- name: Start redis server
  become: yes
  command: service redis start

- name: Run application tests
  command: npm test
  args:
    chdir: /home/vagrant/userapi
  # Register the output of the module in a variable
  register: userapi_test_health

- name: Print userapi test health
  debug:
    msg: "{{ userapi_test_health.stdout.split('\n') }}"

- name: Start application/userapi
  command: pm2 start npm -- start
  args:
    chdir: /home/vagrant/userapi

# - name: Check userapi health
#   uri:
#     url: http://127.0.0.1/-/health
#     return_content: yes
#   # Register the output of the module in a variable
#   register: redis_health
#
# -
#
# - name: Print Redis health
#   debug:
#     msg: "{{ redis_health.content }}"
