---

- name: Start redis server
  command: redis-server --daemonize yes

- name: Run application tests
  command: npm test
  args:
    chdir: /home/vagrant/userapi
  # Register the output of the module in a variable
  register: userapi_test_health

- name: Print userapi test health
  debug:
    msg: "{{ userapi_test_health.stdout.split('\n') }}"

- name: Start application/userapi
  command: pm2 start npm -- start
  args:
    chdir: /home/vagrant/userapi

- name: Check userapi health
  uri:
    url: http://127.0.0.1:3000
    return_content: yes
  # Register the output of the module in a variable
  register: userapi_health

- name: Print userapi server health
  debug:
    msg: "{{ userapi_health.content }}"
