---

- name: Start redis server
  command: redis-server

- name: Run application tests
  command: npm test

- name: Start application/userapi
  command: npm start

# - name: Check userapi health
#   uri:
#     url: http://127.0.0.1/-/health
#     return_content: yes
#   # Register the output of the module in a variable
#   register: redis_health
#
# -
#
# - name: Print Redis health
#   debug:
#     msg: "{{ redis_health.content }}"
