apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-audouypoulain-deployment
  labels:
    app: devops-audouypoulain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-audouypoulain
  template:
    metadata:
      labels:
        app: devops-audouypoulain
    spec:
      volumes: 
        - name: persistent-vol-devops
          persistentVolumeClaim:
            claimName: redis-meta
      containers:
        - name: devops-audouypoulain-container
          image: docker.io/thomaspln/devops_project:latest
          ports: 
            - containerPort: 3000
          imagePullPolicy: Always
        - name: redis-container
          image: redis
          ports:
            - containerPort: 6379
          volumeMounts: 
            - name: persistent-vol-devops
              mountPath: /data
        
