apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-audouypoulain-deployment
  labels:
    app: devops-audouypoulain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-audouypoulain
  template:
    metadata:
      labels:
        app: devops-audouypoulain
    spec:
      volumes: 
      - name:
      containers:
      - name: devops-audouypoulain-container
        image: docker.io/thomaspln/devops_project
        ports: 
        - containerPort: 3002
        imagePullPolicy: Always
      - name: redis-container
        image: redis
        
